apiVersion: v1
kind: Service
metadata:
  name: adminpanel-service
spec:
  selector:
    app: adminpanel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080  
  type: NodePort
